/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class AnadirTrabajador extends javax.swing.JFrame {
    
    
     Connection conexion;
    Statement sentencia;

    /**
     * Creates new form AnadirTrabajador
     */
    
    private String id_admin;
    private ArrayList<String> p_nom = new ArrayList<String>();
    private ArrayList<String> p_cant = new ArrayList<>();
    private ArrayList<String> p_pn = new ArrayList<>();
    private ArrayList<String> p_p = new ArrayList<>();
    private double T_a, pago;
    
    public AnadirTrabajador(String id_admin, ArrayList p_nom, ArrayList p_cant, ArrayList p_pn, ArrayList p_p, double T_a, double pago) {
        initComponents();
        conectatarBaseDatos();
        setLocationRelativeTo(null);
        this.id_admin = id_admin;
        this.p_nom = p_nom;
        this.p_cant = p_cant;
        this.p_pn = p_pn;
        this.p_p = p_p;
        this.T_a = T_a;
        this.pago = pago;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     
    public void conectatarBaseDatos() {
      
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver"); //Linea que carga el driver
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar Dirver");
        }
        try {
  conexion = DriverManager.getConnection("jdbc:ucanaccess://src\\base\\MDB.accdb");
//En esta parte tenemos que cambiar la ruta en la que se encuentra nuestra base de datos 
//Ejemplo "jdbc:ucanaccess://C:\\Proyecto.accdb" hace referencia que esta en el disco local C
            System.out.println(" exitosa");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en la dirección de la base de datos");
        }
        try {
            sentencia = conexion.createStatement();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al crear la conexión con la base de datos");
        }
    }
    
       @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLbl_NombreSU = new javax.swing.JLabel();
        JLbl_ApellidosSU = new javax.swing.JLabel();
        JLbl_TelefonoSU = new javax.swing.JLabel();
        JLbl_ContraSU = new javax.swing.JLabel();
        JLbl_DireccionSU = new javax.swing.JLabel();
        JLbl_ConfirContraSU = new javax.swing.JLabel();
        JTxtF_IDSU = new javax.swing.JTextField();
        JTxtF_TelefonoSU = new javax.swing.JTextField();
        JTxtF_ApellidosSU = new javax.swing.JTextField();
        JTxtF_DireccionSU = new javax.swing.JTextField();
        JBtn_RegistrarSU = new javax.swing.JButton();
        JLbl_DisenoSU = new javax.swing.JLabel();
        JPswdF_ContraSU = new javax.swing.JPasswordField();
        JPswdF_ConfirContraSU = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        JTxtF_NombreSU1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMnB_SignUp = new javax.swing.JMenu();
        JMn_SalirA = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLbl_NombreSU.setText("Nombre:");

        JLbl_ApellidosSU.setText("Apellidos:");

        JLbl_TelefonoSU.setText("Telefono:");

        JLbl_ContraSU.setText("Contraseña:");

        JLbl_DireccionSU.setText("Direccion:");

        JLbl_ConfirContraSU.setText("Confirmar contraseña:");

        JTxtF_IDSU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtF_IDSUKeyTyped(evt);
            }
        });

        JTxtF_TelefonoSU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtF_TelefonoSUKeyTyped(evt);
            }
        });

        JTxtF_ApellidosSU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtF_ApellidosSUKeyTyped(evt);
            }
        });

        JTxtF_DireccionSU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtF_DireccionSUKeyTyped(evt);
            }
        });

        JBtn_RegistrarSU.setText("Registrar");
        JBtn_RegistrarSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_RegistrarSUActionPerformed(evt);
            }
        });

        JLbl_DisenoSU.setText("______________________________________________________________");

        JPswdF_ContraSU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JPswdF_ContraSUKeyTyped(evt);
            }
        });

        JPswdF_ConfirContraSU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JPswdF_ConfirContraSUKeyTyped(evt);
            }
        });

        jLabel1.setText("ID:");

        JTxtF_NombreSU1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtF_NombreSU1KeyTyped(evt);
            }
        });

        JMnB_SignUp.setText("Dar de alta");
        JMnB_SignUp.setEnabled(false);
        jMenuBar1.add(JMnB_SignUp);

        JMn_SalirA.setText("Regresar al menu");
        JMn_SalirA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMn_SalirAMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMn_SalirA);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLbl_DireccionSU)
                            .addComponent(JLbl_TelefonoSU)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JLbl_NombreSU)
                                .addComponent(JLbl_ApellidosSU)
                                .addComponent(jLabel1)))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTxtF_ApellidosSU)
                            .addComponent(JTxtF_TelefonoSU)
                            .addComponent(JTxtF_DireccionSU)
                            .addComponent(JTxtF_IDSU)
                            .addComponent(JTxtF_NombreSU1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLbl_ConfirContraSU)
                            .addComponent(JLbl_ContraSU))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JPswdF_ContraSU, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(JPswdF_ConfirContraSU)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JLbl_DisenoSU))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(JBtn_RegistrarSU, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTxtF_IDSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLbl_NombreSU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTxtF_NombreSU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLbl_ApellidosSU)
                    .addComponent(JTxtF_ApellidosSU, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLbl_TelefonoSU)
                    .addComponent(JTxtF_TelefonoSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLbl_DireccionSU)
                    .addComponent(JTxtF_DireccionSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JLbl_DisenoSU, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPswdF_ContraSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLbl_ContraSU))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLbl_ConfirContraSU)
                    .addComponent(JPswdF_ConfirContraSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(JBtn_RegistrarSU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtn_RegistrarSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_RegistrarSUActionPerformed
        if (JTxtF_IDSU.getText().equals("") || JTxtF_ApellidosSU.getText().equals("") || JTxtF_NombreSU1.getText().equals("") || JTxtF_DireccionSU.getText().equals("") || JPswdF_ConfirContraSU.getPassword().equals("") || JPswdF_ContraSU.getPassword().equals("") || JTxtF_TelefonoSU.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Los campos deben estan llenos");
        } else if (JTxtF_IDSU.getText().length() > 10) {

            JOptionPane.showMessageDialog(null, "El ID tiene que ser menor o igual a 10 digitos");
        } else {
            String nom, ape, pre, cel, id, dire, cont, confir;
            id = JTxtF_IDSU.getText();
            nom = JTxtF_NombreSU1.getText();
            ape = JTxtF_ApellidosSU.getText();
            cel = JTxtF_TelefonoSU.getText();
            dire = JTxtF_DireccionSU.getText();
            cont = Arrays.toString(JPswdF_ContraSU.getPassword());
            char[] arrayPa = JPswdF_ContraSU.getPassword();
            String pass = new String(arrayPa);
            confir = Arrays.toString(JPswdF_ConfirContraSU.getPassword());
            char[] arrayPaC = JPswdF_ConfirContraSU.getPassword();
            String pass2 = new String(arrayPaC);
            if (!id.equals("") || !nom.equals("") || !ape.equals("") || !cel.equals("") || !dire.equals("") || !cont.equals("") || !confir.equals("")) {
                if (Arrays.toString(JPswdF_ContraSU.getPassword()).equals(Arrays.toString(JPswdF_ConfirContraSU.getPassword()))) {
                    String sql = "insert into Trabajador(Id,Nombre,Apellido,Telefono,Direccion,Contraseña) values " + "('" + id + "','" + nom + "','" + ape + "','" + cel + "','" + dire + "','" + pass + "')";
                    try {
                        sentencia.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Trabajador Agregado\n");
                        
                        JTxtF_IDSU.setText(null);
                        JTxtF_NombreSU1.setText(null);
                        JTxtF_ApellidosSU.setText(null);
                        JTxtF_TelefonoSU.setText(null);
                        JTxtF_DireccionSU.setText(null);
                        JPswdF_ContraSU.setText(null);
                        JPswdF_ConfirContraSU.setText(null);
                        
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Error, Ya existe un trabajador con ese ID\n ");
                        System.out.println(ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No coinciden las contraseñas");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Los campos deben de estar llenos");
            }
        }
        
    }//GEN-LAST:event_JBtn_RegistrarSUActionPerformed

    private void JTxtF_IDSUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtF_IDSUKeyTyped
        char bb=evt.getKeyChar();
        
        if(Character.isLetter(bb)){
           getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros\n");
        } 
        if(JTxtF_IDSU.getText().length()>=9){
            evt.consume();
        }
    }//GEN-LAST:event_JTxtF_IDSUKeyTyped

    private void JTxtF_ApellidosSUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtF_ApellidosSUKeyTyped
        if(JTxtF_ApellidosSU.getText().length()>=45){
            evt.consume();
        }
    }//GEN-LAST:event_JTxtF_ApellidosSUKeyTyped

    private void JTxtF_TelefonoSUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtF_TelefonoSUKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_JTxtF_TelefonoSUKeyTyped

    private void JTxtF_DireccionSUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtF_DireccionSUKeyTyped
        if(JTxtF_DireccionSU.getText().length()>=60){
            evt.consume();
        }
    }//GEN-LAST:event_JTxtF_DireccionSUKeyTyped

    private void JPswdF_ContraSUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPswdF_ContraSUKeyTyped
        if(JPswdF_ContraSU.getPassword().length>=15){
            evt.consume();
        }
    }//GEN-LAST:event_JPswdF_ContraSUKeyTyped

    private void JPswdF_ConfirContraSUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPswdF_ConfirContraSUKeyTyped
        if(JPswdF_ConfirContraSU.getPassword().length>=15){
            evt.consume();
        }
    }//GEN-LAST:event_JPswdF_ConfirContraSUKeyTyped

    private void JTxtF_NombreSU1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtF_NombreSU1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtF_NombreSU1KeyTyped

    private void JMn_SalirAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMn_SalirAMouseClicked
        Ventas ven=new Ventas(id_admin, 1, p_nom, p_cant, p_pn, p_p, T_a, pago);//Mostramos el otro JFrame y ocultamos este
        ven.setVisible(true);
        ven.setEnabled(true);
        this.setVisible(false);
        this.setEnabled(false);
    }//GEN-LAST:event_JMn_SalirAMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnadirTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnadirTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnadirTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnadirTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<String> nulo = new ArrayList<>();
                new AnadirTrabajador("", nulo, nulo, nulo, nulo, 0, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn_RegistrarSU;
    private javax.swing.JLabel JLbl_ApellidosSU;
    private javax.swing.JLabel JLbl_ConfirContraSU;
    private javax.swing.JLabel JLbl_ContraSU;
    private javax.swing.JLabel JLbl_DireccionSU;
    private javax.swing.JLabel JLbl_DisenoSU;
    private javax.swing.JLabel JLbl_NombreSU;
    private javax.swing.JLabel JLbl_TelefonoSU;
    private javax.swing.JMenu JMnB_SignUp;
    private javax.swing.JMenu JMn_SalirA;
    private javax.swing.JPasswordField JPswdF_ConfirContraSU;
    private javax.swing.JPasswordField JPswdF_ContraSU;
    private javax.swing.JTextField JTxtF_ApellidosSU;
    private javax.swing.JTextField JTxtF_DireccionSU;
    private javax.swing.JTextField JTxtF_IDSU;
    private javax.swing.JTextField JTxtF_NombreSU1;
    private javax.swing.JTextField JTxtF_TelefonoSU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
