
package interfaz;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class BajarTrabajador extends javax.swing.JFrame {
    private Connection conexion;
    private Statement sentencia;
    private String id_admin;
    private ArrayList<String> p_nom = new ArrayList<>();
    private ArrayList<String> p_cant = new ArrayList<>();
    private ArrayList<String> p_pn = new ArrayList<>();
    private ArrayList<String> p_p = new ArrayList<>();
    private double T_a, pago;
    
    
    //constructor
    public BajarTrabajador(String id_admin, ArrayList p_nom, ArrayList p_cant, ArrayList p_pn, ArrayList p_p, double T_a, double pago) {
        initComponents();
        conectatarBaseDatos();
        setLocationRelativeTo(null);
        this.id_admin = id_admin;
        this.p_nom = p_nom;
        this.p_cant = p_cant;
        this.p_pn = p_pn;
        this.p_p = p_p;
        this.T_a = T_a;
        this.pago = pago;
    }

    private void conectatarBaseDatos() {

        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver"); //Linea que carga el driver
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar Dirver");
        }
        try {
            conexion = DriverManager.getConnection("jdbc:ucanaccess://src\\base\\MDB.accdb");
        //En esta parte tenemos que cambiar la ruta en la que se encuentra nuestra base de datos 
        //Ejemplo "jdbc:ucanaccess://C:\\Proyecto.accdb" hace referencia que esta en el disco local C
            System.out.println(" exitosa");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en la dirección de la base de datos");
        }
        try {
            sentencia = conexion.createStatement();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al crear la conexión con la base de datos");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLbl_BajaTraID = new javax.swing.JLabel();
        JTxtF_EliminarSU = new javax.swing.JTextField();
        JBtn_Eliminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMn_Eliminar = new javax.swing.JMenu();
        JMn_SalirB = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLbl_BajaTraID.setText("ID:");

        JTxtF_EliminarSU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtF_EliminarSUKeyTyped(evt);
            }
        });

        JBtn_Eliminar.setText("Eliminar");
        JBtn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_EliminarActionPerformed(evt);
            }
        });

        JMn_Eliminar.setText("Eliminar usuario");
        JMn_Eliminar.setEnabled(false);
        jMenuBar1.add(JMn_Eliminar);

        JMn_SalirB.setText("Regresar al menu");
        JMn_SalirB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMn_SalirBMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMn_SalirB);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(JLbl_BajaTraID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBtn_Eliminar)
                    .addComponent(JTxtF_EliminarSU, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtF_EliminarSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLbl_BajaTraID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(JBtn_Eliminar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTxtF_EliminarSUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtF_EliminarSUKeyTyped
        char bb=evt.getKeyChar();
        
        if(Character.isLetter(bb)){
           getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros\n");
        }
        
        if(JTxtF_EliminarSU.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_JTxtF_EliminarSUKeyTyped

    private void JMn_SalirBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMn_SalirBMouseClicked
        Ventas ven=new Ventas(id_admin, 1, p_nom, p_cant, p_pn, p_p, T_a, pago);//Mostramos el otro JFrame y ocultamos este
        ven.setVisible(true);
        ven.setEnabled(true);
        this.setVisible(false);
        this.setEnabled(false);
    }//GEN-LAST:event_JMn_SalirBMouseClicked

    private void JBtn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_EliminarActionPerformed
        String DeleteID = JTxtF_EliminarSU.getText();
        if(DeleteID.equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese un ID en el campo", "Error campo vacio", 0);
            return;
        }
        try {
            String sql = "DELETE FROM Trabajador WHERE Id= '" + DeleteID + "'";
            int numAffectColum = sentencia.executeUpdate(sql);
            if (numAffectColum == 0) {
                JOptionPane.showMessageDialog(null, "No se encontro un trabajador con este ID", "No se encontro trabajador", 1);
                JTxtF_EliminarSU.setText(null);
            } else {
                JOptionPane.showMessageDialog(null, "Trabajador borrado con exito", "Se elimino trabajador", 1);
                JTxtF_EliminarSU.setText(null);
            }
        } catch (SQLException ex) {
            Logger.getLogger(BajarTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBtn_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BajarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BajarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BajarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BajarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<String> nulo = new ArrayList<>();
                new BajarTrabajador("", nulo, nulo, nulo, nulo, 0, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn_Eliminar;
    private javax.swing.JLabel JLbl_BajaTraID;
    private javax.swing.JMenu JMn_Eliminar;
    private javax.swing.JMenu JMn_SalirB;
    private javax.swing.JTextField JTxtF_EliminarSU;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
