/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ConsultarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarUsuario
     */
    
      Connection conexion;
    Statement sentencia;
    
    private String id_admin;
    private ArrayList<String> p_nom = new ArrayList<>();
    private ArrayList<String> p_cant = new ArrayList<>();
    private ArrayList<String> p_pn = new ArrayList<>();
    private ArrayList<String> p_p = new ArrayList<>();
    private double T_a, pago;

    public ConsultarUsuario(String id_admin, ArrayList p_nom, ArrayList p_cant, ArrayList p_pn, ArrayList p_p, double T_a, double pago) {
        initComponents();
        setLocationRelativeTo(null);
        conectatarBaseDatos();
        this.id_admin = id_admin;
        this.p_nom = p_nom;
        this.p_cant = p_cant;
        this.p_pn = p_pn;
        this.p_p = p_p;
        this.T_a = T_a;
        this.pago = pago;
    }
    
      
    public void conectatarBaseDatos() {
      
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver"); //Linea que carga el driver
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar Dirver");
        }
        try {
  conexion = DriverManager.getConnection("jdbc:ucanaccess://src\\base\\MDB.accdb");
//En esta parte tenemos que cambiar la ruta en la que se encuentra nuestra base de datos 
//Ejemplo "jdbc:ucanaccess://C:\\Proyecto.accdb" hace referencia que esta en el disco local C
            System.out.println(" exitosa");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en la dirección de la base de datos");
        }
        try {
            sentencia = conexion.createStatement();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al crear la conexión con la base de datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTxtF_ApellidosCon = new javax.swing.JTextField();
        JLbl_NombreSU = new javax.swing.JLabel();
        JTxtF_DireccionCon = new javax.swing.JTextField();
        JLbl_ApellidosSU = new javax.swing.JLabel();
        JLbl_TelefonoSU = new javax.swing.JLabel();
        JLbl_DireccionSU = new javax.swing.JLabel();
        JTxtF_IDCon = new javax.swing.JTextField();
        JTxtF_TelefonoCon = new javax.swing.JTextField();
        JBtn_ConsultarSU = new javax.swing.JButton();
        JLbl_IDCon = new javax.swing.JLabel();
        JTxtF_NombreCon = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMn_ConsultarSU = new javax.swing.JMenu();
        JMn_SalirConUsu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTxtF_ApellidosCon.setEnabled(false);
        JTxtF_ApellidosCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtF_ApellidosConKeyTyped(evt);
            }
        });

        JLbl_NombreSU.setText("Nombre:");

        JTxtF_DireccionCon.setEnabled(false);
        JTxtF_DireccionCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtF_DireccionConKeyTyped(evt);
            }
        });

        JLbl_ApellidosSU.setText("Apellidos:");

        JLbl_TelefonoSU.setText("Telefono:");

        JLbl_DireccionSU.setText("Direccion:");

        JTxtF_IDCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtF_IDConKeyTyped(evt);
            }
        });

        JTxtF_TelefonoCon.setEnabled(false);
        JTxtF_TelefonoCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtF_TelefonoConKeyTyped(evt);
            }
        });

        JBtn_ConsultarSU.setText("Consultar");
        JBtn_ConsultarSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_ConsultarSUActionPerformed(evt);
            }
        });

        JLbl_IDCon.setText("ID:");

        JTxtF_NombreCon.setEnabled(false);
        JTxtF_NombreCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtF_NombreConKeyTyped(evt);
            }
        });

        JMn_ConsultarSU.setText("Consultar usuario");
        JMn_ConsultarSU.setEnabled(false);
        jMenuBar1.add(JMn_ConsultarSU);

        JMn_SalirConUsu.setText("Regresar al menu");
        JMn_SalirConUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMn_SalirConUsuMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMn_SalirConUsu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLbl_IDCon)
                    .addComponent(JLbl_DireccionSU)
                    .addComponent(JLbl_TelefonoSU)
                    .addComponent(JLbl_ApellidosSU)
                    .addComponent(JLbl_NombreSU))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTxtF_NombreCon, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(JTxtF_ApellidosCon)
                    .addComponent(JTxtF_TelefonoCon)
                    .addComponent(JTxtF_DireccionCon)
                    .addComponent(JTxtF_IDCon))
                .addGap(43, 43, 43)
                .addComponent(JBtn_ConsultarSU)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtn_ConsultarSU)
                    .addComponent(JLbl_IDCon)
                    .addComponent(JTxtF_IDCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLbl_NombreSU, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(JTxtF_NombreCon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLbl_ApellidosSU)
                    .addComponent(JTxtF_ApellidosCon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLbl_TelefonoSU)
                    .addComponent(JTxtF_TelefonoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLbl_DireccionSU)
                    .addComponent(JTxtF_DireccionCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTxtF_IDConKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtF_IDConKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_JTxtF_IDConKeyTyped

    private void JTxtF_ApellidosConKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtF_ApellidosConKeyTyped
        if(JTxtF_ApellidosCon.getText().length()>=45){
            evt.consume();
        }
    }//GEN-LAST:event_JTxtF_ApellidosConKeyTyped

    private void JTxtF_DireccionConKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtF_DireccionConKeyTyped
        if(JTxtF_DireccionCon.getText().length()>=60){
            evt.consume();
        }
    }//GEN-LAST:event_JTxtF_DireccionConKeyTyped

    private void JTxtF_TelefonoConKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtF_TelefonoConKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_JTxtF_TelefonoConKeyTyped

    private void JBtn_ConsultarSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_ConsultarSUActionPerformed
        
        if(JTxtF_IDCon.getText().equals("")){
            JOptionPane.showMessageDialog(null," Ingresa un ID");
        } else {
            String id = this.JTxtF_IDCon.getText();
            // String datos[] = new String[6];    //Variable que almacena los datos de la consulta
            try {
                PreparedStatement pst = conexion.prepareStatement("SELECT * FROM Trabajador WHERE id= ?");
                pst.setString(1, id);
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {

                    JTxtF_IDCon.setText(rs.getString("id"));
                    JTxtF_NombreCon.setText(rs.getString("Nombre"));
                    JTxtF_ApellidosCon.setText(rs.getString("Apellido"));
                    JTxtF_TelefonoCon.setText(rs.getString("Telefono"));
                    JTxtF_DireccionCon.setText(rs.getString("Contraseña"));

                    JOptionPane.showMessageDialog(null, "Trabajador Encontrado\n");

                } else {
                    JOptionPane.showMessageDialog(null, "Trabajador No Encontrado\n");

                }

            } catch (SQLException ex) {

            }
        }
        
          
    }//GEN-LAST:event_JBtn_ConsultarSUActionPerformed

    private void JTxtF_NombreConKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtF_NombreConKeyTyped
        if(JTxtF_NombreCon.getText().length()>=45){
            evt.consume();
        }
    }//GEN-LAST:event_JTxtF_NombreConKeyTyped

    private void JMn_SalirConUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMn_SalirConUsuMouseClicked
        Ventas ven=new Ventas(id_admin, 1, p_nom, p_cant, p_pn, p_p, T_a, pago);//Mostramos el otro JFrame y ocultamos este
        ven.setVisible(true);
        ven.setEnabled(true);
        this.setVisible(false);
        this.setEnabled(false);
    }//GEN-LAST:event_JMn_SalirConUsuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<String> nulo = new ArrayList<>();
                new ConsultarUsuario("", nulo, nulo, nulo, nulo, 0, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn_ConsultarSU;
    private javax.swing.JLabel JLbl_ApellidosSU;
    private javax.swing.JLabel JLbl_DireccionSU;
    private javax.swing.JLabel JLbl_IDCon;
    private javax.swing.JLabel JLbl_NombreSU;
    private javax.swing.JLabel JLbl_TelefonoSU;
    private javax.swing.JMenu JMn_ConsultarSU;
    private javax.swing.JMenu JMn_SalirConUsu;
    private javax.swing.JTextField JTxtF_ApellidosCon;
    private javax.swing.JTextField JTxtF_DireccionCon;
    private javax.swing.JTextField JTxtF_IDCon;
    private javax.swing.JTextField JTxtF_NombreCon;
    private javax.swing.JTextField JTxtF_TelefonoCon;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
