/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ICI203IA
 */
public class IngresarAdmin extends javax.swing.JFrame {

     Connection conexion;
    Statement sentencia;
    /** Creates new form IngresarAdmin */
    
    private ArrayList<String> p_nom = new ArrayList<>();
    private ArrayList<String> p_cant = new ArrayList<>();
    private ArrayList<String> p_pn = new ArrayList<>();
    private ArrayList<String> p_p = new ArrayList<>();
    private double T_a, pago;
    
    public IngresarAdmin(ArrayList p_nom, ArrayList p_cant, ArrayList p_pn, ArrayList p_p, double T_a, double pago) {
        initComponents();
        conectatarBaseDatos();
        setLocationRelativeTo(null);
        this.p_nom = p_nom;
        this.p_cant = p_cant;
        this.p_pn = p_pn;
        this.p_p = p_p;
        this.T_a = T_a;
        this.pago = pago;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
       
    public void conectatarBaseDatos() {
      
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver"); //Linea que carga el driver
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar Dirver");
        }
        try {
  conexion = DriverManager.getConnection("jdbc:ucanaccess://src\\base\\MDB.accdb");
//En esta parte tenemos que cambiar la ruta en la que se encuentra nuestra base de datos 
//Ejemplo "jdbc:ucanaccess://C:\\Proyecto.accdb" hace referencia que esta en el disco local C
            System.out.println(" exitosa");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en la dirección de la base de datos");
        }
        try {
            sentencia = conexion.createStatement();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al crear la conexión con la base de datos");
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBtn_SalirA = new javax.swing.JButton();
        JLbl_TituloA = new javax.swing.JLabel();
        JLbl_UsuarioA = new javax.swing.JLabel();
        JLbl_ContraA = new javax.swing.JLabel();
        JTxtF_UsuarioA = new javax.swing.JTextField();
        JBtn_AccederA = new javax.swing.JButton();
        JPwdF_ContraA = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBtn_SalirA.setText("Salir");
        JBtn_SalirA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_SalirAActionPerformed(evt);
            }
        });

        JLbl_TituloA.setText("Ingresar como Administrador");

        JLbl_UsuarioA.setText("Usuario");

        JLbl_ContraA.setText("Contraseña");

        JTxtF_UsuarioA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxtF_UsuarioAKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtF_UsuarioAKeyTyped(evt);
            }
        });

        JBtn_AccederA.setText("Acceder");
        JBtn_AccederA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_AccederAActionPerformed(evt);
            }
        });

        JPwdF_ContraA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JPwdF_ContraAKeyPressed(evt);
            }
        });

        jMenu1.setText("Ingresar como Trabajador");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 231, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JBtn_AccederA)
                        .addGap(269, 269, 269))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JBtn_SalirA)
                        .addGap(40, 40, 40))))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLbl_TituloA, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLbl_UsuarioA)
                            .addComponent(JLbl_ContraA))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTxtF_UsuarioA)
                            .addComponent(JPwdF_ContraA, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(JLbl_TituloA)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLbl_UsuarioA)
                    .addComponent(JTxtF_UsuarioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLbl_ContraA)
                    .addComponent(JPwdF_ContraA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(JBtn_AccederA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(JBtn_SalirA)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtn_SalirAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_SalirAActionPerformed
        System.exit(0);//Boton para cerrar la app
    }//GEN-LAST:event_JBtn_SalirAActionPerformed

    private void JBtn_AccederAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_AccederAActionPerformed
        try {
        String usuario=JTxtF_UsuarioA.getText();
        String password=String.valueOf(JPwdF_ContraA.getPassword());

        String query="SELECT * FROM Administrador WHERE Id='"+usuario+"' and Contraseña='"+password+"'";

        sentencia=conexion.createStatement();
        ResultSet rs=sentencia.executeQuery(query);

        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Ingresando...");
            Ventas acceder=new Ventas(usuario, 1, p_nom, p_cant, p_pn, p_p, T_a, pago);//Dentro del if nada mas mostramos el otro JFrame y ocultamos este
            acceder.setVisible(true);
            acceder.setEnabled(true);
            this.setVisible(false);
            this.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Error... Revise sus datos");
        }
    } catch (SQLException ex) {
        Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_JBtn_AccederAActionPerformed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        index camTrabajador=new index();//Mostramos el otro JFrame y ocultamos este
        camTrabajador.setVisible(true);
        camTrabajador.setEnabled(true);
        this.setVisible(false);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenu1MenuSelected

    private void JPwdF_ContraAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPwdF_ContraAKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {//Evaluamos si la tecla presionada sea "ENTER" para acceder.
            try {
            String usuario=JTxtF_UsuarioA.getText();
            String password=String.valueOf(JPwdF_ContraA.getPassword());
            String query="SELECT * FROM Administrador WHERE Id='"+usuario+"' and Contraseña='"+password+"'";
            sentencia=conexion.createStatement();
            ResultSet rs=sentencia.executeQuery(query);
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Ingresando...");
                Ventas acceder=new Ventas(usuario, 1, p_nom, p_cant, p_pn, p_p, T_a, pago);//Dentro del if nada mas mostramos el otro JFrame y ocultamos este
                acceder.setVisible(true);
                acceder.setEnabled(true);
                this.setVisible(false);
                this.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Error... Revise sus datos");
            }
            } catch (SQLException ex) {
                Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
    }//GEN-LAST:event_JPwdF_ContraAKeyPressed

    private void JTxtF_UsuarioAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtF_UsuarioAKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            JPwdF_ContraA.requestFocus();
    }//GEN-LAST:event_JTxtF_UsuarioAKeyPressed

    private void JTxtF_UsuarioAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtF_UsuarioAKeyTyped
         char bb=evt.getKeyChar();
        
        if(Character.isLetter(bb)){
           getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros\n");
        } 
    }//GEN-LAST:event_JTxtF_UsuarioAKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<String> nulo = new ArrayList<>();
                new IngresarAdmin(nulo, nulo, nulo, nulo, 0, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn_AccederA;
    private javax.swing.JButton JBtn_SalirA;
    private javax.swing.JLabel JLbl_ContraA;
    private javax.swing.JLabel JLbl_TituloA;
    private javax.swing.JLabel JLbl_UsuarioA;
    private javax.swing.JPasswordField JPwdF_ContraA;
    private javax.swing.JTextField JTxtF_UsuarioA;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
